framework:
    validation:
                enabled: true
                enable_attributes: true
                auto_mapping:
                    App\Entity\: [ 'App\Entity' ]

        # Enables validator auto-mapping support.
        # For instance, basic validation constraints will be inferred from Doctrine's metadata.
        #auto_mapping:
        #    App\Entity\: []

when@test:
    framework:
        validation:
            not_compromised_password: false
